name: bind_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.1.0+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #ui
  pinput: ^2.2.7
  animations: ^2.0.1
  syncfusion_flutter_pdfviewer: ^20.1.51-beta
  youtube_player_flutter: ^8.0.0
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1



  #state management
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.3
  #firebase
  firebase_core: ^1.4.0
  firebase_auth: ^3.1.0
  cloud_firestore: ^3.1.13
  firebase_storage: ^10.0.1
  firebase_messaging: ^11.2.15
  firebase_dynamic_links: ^4.2.1
  firebase_analytics: ^9.0.3
  cloud_functions: ^3.2.16

  #geo
  google_maps_flutter: ^2.0.6
  google_maps_webservice: ^0.0.20-nullsafety.0
  geolocator: ^8.2.0
  geoflutterfire: ^3.0.1

  algolia: ^1.1.1

  #platform
  file_picker: ^4.2.3
  image_picker: ^0.8.4+1
  android_intent: ^2.0.2 
  shared_preferences: ^2.0.6
  camera: ^0.9.2
  image_cropper: ^2.0.0
  url_launcher: ^6.0.10
  share_plus: ^4.0.4
  fluttertoast: ^8.0.8
  flutter_native_image: ^0.0.6+1

  #google sign-in
  google_sign_in: ^5.2.1

  
  http: ^0.13.2

  #payment
  razorpay_flutter: ^1.2.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/launcher/launcher.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: EuclidSquare
      fonts:
        - asset: fonts/EuclidSquare-Bold.ttf
        - asset: fonts/EuclidSquare-BoldItalic.ttf
        - asset: fonts/EuclidSquare-Italic.ttf
        - asset: fonts/EuclidSquare-Light.ttf
        - asset: fonts/EuclidSquare-LightItalic.ttf
        - asset: fonts/EuclidSquare-Medium.ttf
        - asset: fonts/EuclidSquare-MediumItalic.ttf
        - asset: fonts/EuclidSquare-Regular.ttf
        - asset: fonts/EuclidSquare-SemiBold.ttf
        - asset: fonts/EuclidSquare-SemiBoldItalic.ttf
